---
title: "Format data shiny"
output: html_document
date: "2023-02-05"
author: Antonio Parraga Leo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load data
#setwd('Documents/UCSF/shiny_npj/')
metadata <- read.delim('metadata_train.csv', sep = ',', row.names = 1)
metadata
```
```{r}
table(metadata %>% filter(trimester == 1 & NIH.Racial.Category == "White" & 
                            project%in%c('A','B','C','D')) %>% .$Type)

count(metadata,NIH.Racial.Category) %>%
   arrange(desc(NIH.Racial.Category)) %>%
  mutate(prop = n / sum(.$n) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop )
```

```{r}
diver <- read.delim('diversity_train.csv', sep = ',')
diver

corr <- round(cor(diver[-1]), 1)
corr
ggcorrplot::ggcorrplot(corr, hc.order = TRUE, type = "lower",
     outline.col = "white", lab = TRUE,lab_col = 'white',
     colors = c("#6D9EC1", "white", "#E46726"))
```

```{r}
rownames(diver) <- diver$specimen
diver <- diver[metadata$specimen,]
diver_metadata <- cbind(diver,metadata[-1])

ggpairs(data = diver_metadata, columns = c('shannon','inv_simpson'),
        aes(colour = Type),
        upper = list(continuous = wrap("cor", size = 6)))+
      scale_fill_manual(labels = c('Preterm','Term'),
                        values = c('#CBC3E3','grey')) +
  scale_colour_manual(labels = c('Preterm','Term'),
                        values = c('#CBC3E3','grey'))+
  theme_bw()+
  theme(strip.text.x = element_text(size = 20),
           strip.text.y = element_text(size = 20))
```
```{r}
library(umap)
head(iris)
iris[, grep("Sepal|Petal", colnames(iris))]
```

```{r}
phylotypes <- read.csv('Pt5e_1.combined.pseudocounts.csv', row.names = 1)
phylotypes
```

```{r}
library(ecodist)
phylo_distance <- bcdist(phylotypes)
str(phylo_distance)
```

```{r}
library(reticulate)
library(umap)
umap.defaults
```


```{r}
phylo_umap <- umap(d = phylotypes,method = 'umap-learn', metric = 'braycurtis',
                   n_neighbors = 45, n_components = 2, min_dist = 1, spread = 1.1)
```


```{r}
library(tidyverse)
umap_df <- phylo_umap$layout %>%
  as.data.frame()%>%
  rename(UMAP1="V1",
         UMAP2="V2") %>%
  mutate(specimen=rownames(phylotypes)) %>%
  inner_join(metadata, by='specimen')
umap_df
```


```{r}
ggplot(umap_df, aes(x = UMAP1, 
             y = UMAP2, 
             color = Type))+
  geom_point()+
  labs(x = "UMAP1",
       y = "UMAP2",
      title = "UMAP plot")+
  theme_bw()
```

```{r}
my_colors_race <- brewer.pal(6,'Dark2')
names(my_colors_race) <- unique(metadata$NIH.Racial.Category)

max(metadata$age)

```


```{r}

my_colors_project <- brewer.pal(10,'Paired')
names(my_colors_project) <- unique(metadata$project)

my_colors_type <- c('Term' = 'grey',
                   'Preterm' = '#CBC3E3')

ifelse('project' == 'project', my_colors_project, my_colors_type)
```

```{r}
 if('project' == 'project'){
      my_colors <- my_colors_project
    } else {
      my_colors <- my_colors_type
    }

my_colors
    
```

```{r}
metadata %>% filter(!age %in% c('Unknown','Below_18','Above_38')) %>% summarise(max = min(age))
metadata$age2 <- str_replace_all(metadata$age, c('Below_18' = '17', 'Above_38' = '39', '18_to_28' = '23','29-38' = '34'))
metadata %>% filter(age2 == 'Unknown')

table(metadata$age2)
```

```{r}
cst_alluvia <- read.delim('cst2alluvia_filtered.csv',
                          sep = ',')
table(cst_alluvia$age)
str_replace_all(cst_alluvia$age, c('Below_18' = '17', 'Above_38' = '39', '18_to_28' = '23'))
```

```{r}
specie <- c(rep("sorgho" , 3) , rep("poacee" , 3) , rep("banana" , 3) , rep("triticum" , 3) )
condition <- rep(c("normal" , "stress" , "Nitrogen") , 4)
value <- abs(rnorm(12 , 0 , 15))
data <- data.frame(specie,condition,value)
```

```{r}

feature = 'Range'

values <- unique(cst_alluvia2[,feature])

list_df <- lapply(values, function(x){
  
  print(x)
  
  df <- cst_alluvia2[cst_alluvia2[,feature] == x,]
  
  to_plot <- df[,c("Trimester","participant_id","CST")]
  df_freq <- to_plot %>% group_by(participant_id,Trimester,CST) %>% summarise(Freq = n())
  df_freq <- df_freq %>%
        group_by(Trimester) %>%
        mutate(pct = Freq / sum(Freq)*100)
  
  
  p <- ggplot(df_freq,
                   aes(x = Trimester, stratum = CST, alluvium = participant_id,
                       fill = CST, label = CST, y = pct)) +
        scale_fill_brewer(palette = "Set2") +
        geom_flow(stat = "alluvium", lode.guidance = "frontback") +
        geom_stratum() +
        scale_x_discrete(breaks=c("1","2","3"),
                         labels=c("1 \n(n = 67)", "2 \n(n = 182)", "3 \n(n = 128)")) +
        ggtitle(x)+
        theme_bw()+
        ylab("Freq")+
        theme(legend.position = "none", text = element_text(size = 20))
  return(p)
  
})

ggarrange(plotlist = list_df, ncol=length(list_df), common.legend = TRUE, legend="right")
```
```{r}
cst_alluvia_ept <- cst_alluvia2 %>% filter(delivery_wk < 32)

    df_term <- cst_alluvia2[cst_alluvia2$Type == "term",]
    df_preterm <- cst_alluvia2[cst_alluvia2$Type == "preterm",]


    to_plot_term <- df_term[,c("Trimester","participant_id","CST")]
    term_freq <- to_plot_term %>% group_by(participant_id,Trimester,CST) %>% summarise(Freq = n() )
    term_freq <- term_freq %>%
      group_by(Trimester) %>%
      mutate(pct = Freq / sum(Freq)*100)


    to_plot_preterm <- df_preterm[,c("Trimester","participant_id","CST")]
    preterm_freq <- to_plot_preterm %>% group_by(participant_id,Trimester,CST) %>% summarise(Freq = n() )
    preterm_freq <- preterm_freq %>%
      group_by(Trimester) %>%
      mutate(pct = Freq / sum(Freq)*100)

    to_plot_epreterm <- cst_alluvia_ept[,c("Trimester","participant_id","CST")]
    epreterm_freq <- to_plot_epreterm %>% group_by(participant_id,Trimester,CST) %>% summarise(Freq = n() )
    epreterm_freq <- epreterm_freq %>%
      group_by(Trimester) %>%
      mutate(pct = Freq / sum(Freq)*100)

    p1 <- ggplot(term_freq,
                 aes(x = Trimester, stratum = CST, alluvium = participant_id,
                     fill = CST, label = CST, y = pct)) +
      scale_fill_brewer(palette = "Set2") +
      geom_flow(stat = "alluvium", lode.guidance = "frontback") +
      geom_stratum() +
      scale_x_discrete(breaks=c("1","2","3"),
                       labels=c("1 \n(n = 67)", "2 \n(n = 182)", "3 \n(n = 128)")) +
      ggtitle("Term")+
      theme_bw()+
      ylab("Freq")+
      theme(legend.position = "none", text = element_text(size = 20))

    p2 <- ggplot(preterm_freq,
                 aes(x = Trimester, stratum = CST, alluvium = participant_id,
                     fill = CST, label = CST, y = pct)) +
      scale_fill_brewer(palette = "Set2") +
      geom_flow(stat = "alluvium", lode.guidance = "frontback") +
      geom_stratum() +
      scale_x_discrete(breaks=c("1","2","3"),
                       labels=c("1 \n(n = 43)", "2 \n(n = 88)", "3 \n(n = 75)")) +
      ggtitle("Preterm")+
      ylab("Freq")+
      theme_bw()+
      theme(legend.position = "none",text = element_text(size = 20))

    p3 <- ggplot(epreterm_freq,
                 aes(x = Trimester, stratum = CST, alluvium = participant_id,
                     fill = CST, label = CST, y = pct)) +
      scale_fill_brewer(palette = "Set2") +
      geom_flow(stat = "alluvium", lode.guidance = "frontback") +
      geom_stratum() +
      scale_x_discrete(breaks=c("1","2","3"),
                       labels=c("1 \n(n = 9)", "2 \n(n = 21)", "3 \n(n = 13)")) +
      ggtitle("Early preterm")+
      ylab("Freq")+
      theme_bw()+
      theme(legend.position = "right",text = element_text(size = 20),
            legend.text = element_text(size=15))

    ggarrange(p1, p2, p3, ncol=3, common.legend = TRUE, legend="right")
```

```{r}
diver_all <- read.csv('../Results/diversity_all.csv')
metadata <- read.csv('../Results/metadata_all.csv')
```

```{r}
test <- merge(diver_all, metadata_all, by='specimen')
test2 <- test[,-grep(x = colnames(test), pattern = 'specimen')] %>% group_by(participant_id) %>% summarise(across(everything(), mean),
            .groups = 'drop')
mean(test[test$participant_id == 'A00004','shannon'])
test2
```
```{r}
md_participant <- distinct(metadata[,!colnames(metadata)%in%c('specimen','collect_wk','age')])
sum(duplicated(md_participant$participant_id))
my_duplicated <- unique(md_participant[duplicated(md_participant$participant_id),]$participant_id)

merge(test2,metadata_all[,colnames%in%c(specimen.collect_wk)])
```

```{r}
md_participant[md_participant$participant_id%in%c('D00061','D00028','D00029','D00059'),]
```
```{r}
md_participant_good <- md_participant %>% filter(!participant_id %in% my_duplicated)

md_participant_bad <- md_participant %>% filter(participant_id %in% my_duplicated)

no_duplicated <- do.call('rbind',
                         lapply(unique(metadata$participant_id),
                                function(my_dup){
  
  i <- which.max(metadata[metadata$participant_id == my_dup,'Trimester'])
  metadata[metadata$participant_id == my_dup,][i,]
}))
sum(duplicated(no_duplicated$participant_id))

md_participant <- rbind(md_participant_good,no_duplicated)
sum(duplicated(no_duplicated$participant_id))
```

```{r}
 umap2plot(metadata,phylotypes_umap, 'specimen')
```


```{r}
volcano %>%
  
  # Data wrangling
  as_tibble() %>%
  rowid_to_column(var="X") %>%
  gather(key="Y", value="Z", -1) %>%
  
  # Change Y to numeric
  mutate(Y=as.numeric(gsub("V","",Y)))
```

